### ISSUE TITLE
Overwriting of chapterized mp3 files if chapter titles are the same

### ISSUE THREAD

**Issue by flintstones-fred** [digitalec/sonus#3]
After the chapters are created, the filename of each chapter is set to the "chapter name" in the book. So, if multiple chapters in the book have the same name, then the program overwrites the previous chapters and only keeps one mp3 file per unique chapter name.

**Comment by digitalec** [comment]
This issue was resolved in commit 5ee6809 and released in version 0.4.0.

The track number is now appended to the filename which will prevent same named chapters from being overwritten.

**Comment by flintstones-fred** [comment]
> This issue was resolved in commit [5ee6809](https://github.com/digitalec/sonus/commit/5ee6809427c7c0340efd4ce21d1c81f317bb26ab) and released in version 0.4.0.
> 
> The track number is now appended to the filename which will prevent same named chapters from being overwritten.

Thank you!
