### ISSUE TITLE
Error while extracting - can not pinpoint the exact source of error

### ISSUE THREAD

**Issue by flintstones-fred** [digitalec/sonus#6]
When I try to download a particular book (most books work amazingly well), I get the following error. And unlike previous cases, I can't tell you what is the source of the error. The download seems to happen without issues and maybe the chapterizer fails? I have replicated this on macOS and linux that are using sonus 0.6.3. 

Here is the output:
```
Downloading part 10 of 10... 100%
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/sonus", line 8, in <module>
    sys.exit(main.main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/main.py", line 119, in main
    chapterizer.main(tmpdir.name, output_path, generic, offset, ffmpeg_debug)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/chapterizer.py", line 219, in main
    all_markers = scan_overdrive_metadata(file_list)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sonus/chapterizer.py", line 22, in scan_overdrive_metadata
    audio_data = xmltodict.parse(xmlstring)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 741

```

**Comment by flintstones-fred** [comment]
Book- "Year of the Tiger" and author Alice Wong

**Comment by digitalec** [comment]
Yep, it looks like the chapterizer is failing when it tries to read the XML data embedded in the file.

The XML data contains the data necessary to cut the files and tag them so I'm very curious to see what's up with that book!

I've put a hold on the book so I can investigate it as soon as it's available.

**Comment by cerinawithasea** [comment]
I get a similar error when i use the script only to split into chapters. On every book, like the last 40 
IM pasting in the entire thing but it's just at the end
sonus /Volumes/Books/2merge —output /Volumes/Books/Boo
ks\ to\ Combine
Output will be saved to: /Volumes/Books/chapters
Found 4 files, containing 23 chapters...
Extracting chapter A Selfie As Big As The Ritz from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter It Begins from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter A Lover’s Guide to Meeting Shy Girls; Or; Breakup Record from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter One of Those Life Things from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter Both Boys from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter Where I Am Supposed to Be from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter This Small Written Thing from a-selfie-as-big-as-the-ritz-part-01.mp3
Extracting chapter Beautiful Existence from a-selfie-as-big-as-the-ritz-part-02.mp3
Extracting chapter It’s a Shame About Ray from a-selfie-as-big-as-the-ritz-part-02.mp3
Extracting chapter Dates from a-selfie-as-big-as-the-ritz-part-02.mp3
Extracting chapter Treats from a-selfie-as-big-as-the-ritz-part-02.mp3
Extracting chapter Taxidermy from a-selfie-as-big-as-the-ritz-part-02.mp3
Extracting chapter Penguins from a-selfie-as-big-as-the-ritz-part-02.mp3
Extracting chapter Toxic Shock Syndrome from a-selfie-as-big-as-the-ritz-part-03.mp3
Extracting chapter Here’s to You from a-selfie-as-big-as-the-ritz-part-03.mp3
Extracting chapter Sundaes at the Tipping Yard from a-selfie-as-big-as-the-ritz-part-03.mp3
Extracting chapter Safe Spaces from a-selfie-as-big-as-the-ritz-part-03.mp3
Extracting chapter A Single Lady’s Manual for Parent-Teacher Evening from a-selfie-as-big-as-the-ritz-part-04.mp3
Extracting chapter A Selfie as Big as the Ritz from a-selfie-as-big-as-the-ritz-part-04.mp3
Extracting chapter The Getting of the Cat from a-selfie-as-big-as-the-ritz-part-04.mp3
Extracting chapter As Understood by the Women from a-selfie-as-big-as-the-ritz-part-04.mp3
Extracting chapter Tributaries from a-selfie-as-big-as-the-ritz-part-04.mp3
Extracting chapter Credits from a-selfie-as-big-as-the-ritz-part-04.mp3
Processing audiobook "A Selfie as Big as the Ritz - Stories" by Lara Williams
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/1 A Selfie As Big As The Ritz.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/2 It Begins.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/3 A Lover’s Guide to Meeting Shy Girls; Or; Breakup Record.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/4 One of Those Life Things.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/5 Both Boys.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/6 Where I Am Supposed to Be.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/7 This Small Written Thing.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/8 Beautiful Existence.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/9 It’s a Shame About Ray.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/10 Dates.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/11 Treats.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/12 Taxidermy.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/13 Penguins.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/14 Toxic Shock Syndrome.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/15 Here’s to You.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/16 Sundaes at the Tipping Yard.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/17 Safe Spaces.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/18 A Single Lady’s Manual for Parent-Teacher Evening.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/19 A Selfie as Big as the Ritz.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/20 The Getting of the Cat.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/21 As Understood by the Women.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/22 Tributaries.mp3
Saving chapter to /Volumes/Books/chapters/Lara Williams/A Selfie as Big as the Ritz - Stories/23 Credits.mp3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/sonus", line 8, in <module>
    sys.exit(main.main())
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/main.py", line 99, in main
    chapterizer.main(arg, output_path, generic, offset, ffmpeg_debug)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/chapterizer.py", line 219, in main
    all_markers = scan_overdrive_metadata(file_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sonus/chapterizer.py", line 21, in scan_overdrive_metadata
    xmlstring = str(tag_data['TXXX:OverDrive MediaMarkers'])
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mutagen/_util.py", line 537, in __getitem__
    return self.__dict[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'TXXX:OverDrive MediaMarkers'
cerinawithasea@Cerinas-MacBook-Pro chapters %

**Comment by cerinawithasea** [comment]
I can get the book back if you need it

**Comment by cerinawithasea** [comment]
I knew to hold on to the files because of this thread, i wondered did you ever get the book? i can grab it anytime

**Comment by digitalec** [comment]
This is all set. There was an `&` in one of the text strings within the XML data and this is an invalid character in XML (it's an escape character).
